require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.colorscheme'
require 'user.treesitter'
require 'user.autopairs'
require 'user.indent'
-- require 'user.gitsigns'
